image: docker:latest

services:
  - docker:19.03.5-dind

  
build-master:
  stage: build
  environment:
    name: production
    url: http://website.com/
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

build-azure:
  stage: build
  environment:
    name: production
    url: http://website.com/
  before_script:
    - docker login -u $CI_REGISTRY_USER_AZURE -p $CI_REGISTRY_PASSWORD_AZURE dockerschool.azurecr.io
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker tag "$CI_REGISTRY_IMAGE" dockerschool.azurecr.io/samples/docker-school
    - docker push dockerschool.azurecr.io/samples/docker-school
  only:
    - azure

build-test:
  stage: build
  environment:
    name: Development
    url: http://website.com/
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - test